// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.5
// source: protos/domain/education.grpc.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EducationGrpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" gorm:"column:education_id;primary_key;"
	EducationId string `protobuf:"bytes,1,opt,name=education_id,json=educationId,proto3" json:"id" gorm:"column:education_id;primary_key;"`
	// @inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
	JobSeekerId string `protobuf:"bytes,2,opt,name=job_seeker_id,json=jobSeekerId,proto3" json:"jobSeekerId" gorm:"column:job_seeker_id;"`
	// @inject_tag: json:"school" gorm:"column:school;"
	School string `protobuf:"bytes,3,opt,name=school,proto3" json:"school" gorm:"column:school;"`
	// @inject_tag: json:"fieldOfStudy" gorm:"column:field_of_study;"
	FieldOfStudy string `protobuf:"bytes,4,opt,name=field_of_study,json=fieldOfStudy,proto3" json:"fieldOfStudy" gorm:"column:field_of_study;"`
	// @inject_tag: json:"description" gorm:"column:description;"
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description" gorm:"column:description;"`
}

func (x *EducationGrpc) Reset() {
	*x = EducationGrpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_domain_education_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EducationGrpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EducationGrpc) ProtoMessage() {}

func (x *EducationGrpc) ProtoReflect() protoreflect.Message {
	mi := &file_protos_domain_education_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EducationGrpc.ProtoReflect.Descriptor instead.
func (*EducationGrpc) Descriptor() ([]byte, []int) {
	return file_protos_domain_education_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *EducationGrpc) GetEducationId() string {
	if x != nil {
		return x.EducationId
	}
	return ""
}

func (x *EducationGrpc) GetJobSeekerId() string {
	if x != nil {
		return x.JobSeekerId
	}
	return ""
}

func (x *EducationGrpc) GetSchool() string {
	if x != nil {
		return x.School
	}
	return ""
}

func (x *EducationGrpc) GetFieldOfStudy() string {
	if x != nil {
		return x.FieldOfStudy
	}
	return ""
}

func (x *EducationGrpc) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type JobseekerEducationGrpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Educations []*EducationGrpc `protobuf:"bytes,2,rep,name=educations,proto3" json:"educations,omitempty"`
}

func (x *JobseekerEducationGrpc) Reset() {
	*x = JobseekerEducationGrpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_domain_education_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobseekerEducationGrpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobseekerEducationGrpc) ProtoMessage() {}

func (x *JobseekerEducationGrpc) ProtoReflect() protoreflect.Message {
	mi := &file_protos_domain_education_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobseekerEducationGrpc.ProtoReflect.Descriptor instead.
func (*JobseekerEducationGrpc) Descriptor() ([]byte, []int) {
	return file_protos_domain_education_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *JobseekerEducationGrpc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobseekerEducationGrpc) GetEducations() []*EducationGrpc {
	if x != nil {
		return x.Educations
	}
	return nil
}

var File_protos_domain_education_grpc_proto protoreflect.FileDescriptor

var file_protos_domain_education_grpc_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0xb6, 0x01, 0x0a, 0x0d, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x47, 0x72, 0x70, 0x63, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x64, 0x75,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6a, 0x6f, 0x62, 0x5f,
	0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63,
	0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66,
	0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x66, 0x53, 0x74, 0x75, 0x64, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x16,
	0x4a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x47, 0x72, 0x70, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x0a, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x64, 0x75, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x70, 0x63, 0x52, 0x0a, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x73, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_domain_education_grpc_proto_rawDescOnce sync.Once
	file_protos_domain_education_grpc_proto_rawDescData = file_protos_domain_education_grpc_proto_rawDesc
)

func file_protos_domain_education_grpc_proto_rawDescGZIP() []byte {
	file_protos_domain_education_grpc_proto_rawDescOnce.Do(func() {
		file_protos_domain_education_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_domain_education_grpc_proto_rawDescData)
	})
	return file_protos_domain_education_grpc_proto_rawDescData
}

var file_protos_domain_education_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_domain_education_grpc_proto_goTypes = []interface{}{
	(*EducationGrpc)(nil),          // 0: protos.domain.EducationGrpc
	(*JobseekerEducationGrpc)(nil), // 1: protos.domain.JobseekerEducationGrpc
}
var file_protos_domain_education_grpc_proto_depIdxs = []int32{
	0, // 0: protos.domain.JobseekerEducationGrpc.educations:type_name -> protos.domain.EducationGrpc
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_domain_education_grpc_proto_init() }
func file_protos_domain_education_grpc_proto_init() {
	if File_protos_domain_education_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_domain_education_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EducationGrpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_domain_education_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobseekerEducationGrpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_domain_education_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_domain_education_grpc_proto_goTypes,
		DependencyIndexes: file_protos_domain_education_grpc_proto_depIdxs,
		MessageInfos:      file_protos_domain_education_grpc_proto_msgTypes,
	}.Build()
	File_protos_domain_education_grpc_proto = out.File
	file_protos_domain_education_grpc_proto_rawDesc = nil
	file_protos_domain_education_grpc_proto_goTypes = nil
	file_protos_domain_education_grpc_proto_depIdxs = nil
}
