// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protos/domain/employment_type.grpc.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobSeekerEmploymentType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" gorm:"column:job_seeker_employment_type_id;primary_key;"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
	JobSeekerId string `protobuf:"bytes,2,opt,name=job_seeker_id,json=jobSeekerId,proto3" json:"job_seeker_id,omitempty"`
	// @inject_tag: json:"employmentTypeId" gorm:"column:employment_type_id;"
	EmploymentTypeId int32 `protobuf:"varint,3,opt,name=employment_type_id,json=employmentTypeId,proto3" json:"employment_type_id,omitempty"`
	// @inject_tag: json:"employmentType" gorm:"column:employment_type;"
	EmploymentType string `protobuf:"bytes,4,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
}

func (x *JobSeekerEmploymentType) Reset() {
	*x = JobSeekerEmploymentType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_domain_employment_type_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerEmploymentType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerEmploymentType) ProtoMessage() {}

func (x *JobSeekerEmploymentType) ProtoReflect() protoreflect.Message {
	mi := &file_protos_domain_employment_type_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerEmploymentType.ProtoReflect.Descriptor instead.
func (*JobSeekerEmploymentType) Descriptor() ([]byte, []int) {
	return file_protos_domain_employment_type_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *JobSeekerEmploymentType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobSeekerEmploymentType) GetJobSeekerId() string {
	if x != nil {
		return x.JobSeekerId
	}
	return ""
}

func (x *JobSeekerEmploymentType) GetEmploymentTypeId() int32 {
	if x != nil {
		return x.EmploymentTypeId
	}
	return 0
}

func (x *JobSeekerEmploymentType) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

var File_protos_domain_employment_type_grpc_proto protoreflect.FileDescriptor

var file_protos_domain_employment_type_grpc_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xa4, 0x01, 0x0a, 0x17, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x7b, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2e, 0x6a,
	0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x42, 0x1d, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x73, 0x65, 0x65,
	0x6b, 0x65, 0x72, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_domain_employment_type_grpc_proto_rawDescOnce sync.Once
	file_protos_domain_employment_type_grpc_proto_rawDescData = file_protos_domain_employment_type_grpc_proto_rawDesc
)

func file_protos_domain_employment_type_grpc_proto_rawDescGZIP() []byte {
	file_protos_domain_employment_type_grpc_proto_rawDescOnce.Do(func() {
		file_protos_domain_employment_type_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_domain_employment_type_grpc_proto_rawDescData)
	})
	return file_protos_domain_employment_type_grpc_proto_rawDescData
}

var file_protos_domain_employment_type_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_domain_employment_type_grpc_proto_goTypes = []interface{}{
	(*JobSeekerEmploymentType)(nil), // 0: protos.domain.JobSeekerEmploymentType
}
var file_protos_domain_employment_type_grpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_domain_employment_type_grpc_proto_init() }
func file_protos_domain_employment_type_grpc_proto_init() {
	if File_protos_domain_employment_type_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_domain_employment_type_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerEmploymentType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_domain_employment_type_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_domain_employment_type_grpc_proto_goTypes,
		DependencyIndexes: file_protos_domain_employment_type_grpc_proto_depIdxs,
		MessageInfos:      file_protos_domain_employment_type_grpc_proto_msgTypes,
	}.Build()
	File_protos_domain_employment_type_grpc_proto = out.File
	file_protos_domain_employment_type_grpc_proto_rawDesc = nil
	file_protos_domain_employment_type_grpc_proto_goTypes = nil
	file_protos_domain_employment_type_grpc_proto_depIdxs = nil
}
