// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.5
// source: protos/domain/skill.grpc.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobSeekerSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" gorm:"column:job_seeker_skill_id;primary_key;"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" gorm:"column:job_seeker_skill_id;primary_key;"`
	// @inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
	JobSeekerId string `protobuf:"bytes,2,opt,name=job_seeker_id,json=jobSeekerId,proto3" json:"jobSeekerId" gorm:"column:job_seeker_id;"`
	// @inject_tag: json:"skillId" gorm:"column:skill_id;"
	SkillId string `protobuf:"bytes,3,opt,name=skill_id,json=skillId,proto3" json:"skillId" gorm:"column:skill_id;"`
	// @inject_tag: json:"skill" gorm:"column:skill;"
	Skill string `protobuf:"bytes,4,opt,name=skill,proto3" json:"skill" gorm:"column:skill;"`
	// @inject_tag: json:"levelId" gorm:"column:level_id;"
	LevelId int32 `protobuf:"varint,5,opt,name=level_id,json=levelId,proto3" json:"levelId" gorm:"column:level_id;"`
	// @inject_tag: json:"level" gorm:"column:level;"
	Level string `protobuf:"bytes,6,opt,name=level,proto3" json:"level" gorm:"column:level;"`
}

func (x *JobSeekerSkill) Reset() {
	*x = JobSeekerSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_domain_skill_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobSeekerSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSeekerSkill) ProtoMessage() {}

func (x *JobSeekerSkill) ProtoReflect() protoreflect.Message {
	mi := &file_protos_domain_skill_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSeekerSkill.ProtoReflect.Descriptor instead.
func (*JobSeekerSkill) Descriptor() ([]byte, []int) {
	return file_protos_domain_skill_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *JobSeekerSkill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobSeekerSkill) GetJobSeekerId() string {
	if x != nil {
		return x.JobSeekerId
	}
	return ""
}

func (x *JobSeekerSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *JobSeekerSkill) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *JobSeekerSkill) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *JobSeekerSkill) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_protos_domain_skill_grpc_proto protoreflect.FileDescriptor

var file_protos_domain_skill_grpc_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0xa6, 0x01, 0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6a, 0x6f, 0x62, 0x5f, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x53, 0x65,
	0x65, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x72, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e,
	0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2e, 0x6a, 0x6f, 0x62, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x14, 0x4a, 0x6f,
	0x62, 0x53, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x50, 0x01, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x61, 0x6e, 0x70, 0x6e, 0x67, 0x2f, 0x6a, 0x6f, 0x62, 0x2d, 0x73, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_domain_skill_grpc_proto_rawDescOnce sync.Once
	file_protos_domain_skill_grpc_proto_rawDescData = file_protos_domain_skill_grpc_proto_rawDesc
)

func file_protos_domain_skill_grpc_proto_rawDescGZIP() []byte {
	file_protos_domain_skill_grpc_proto_rawDescOnce.Do(func() {
		file_protos_domain_skill_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_domain_skill_grpc_proto_rawDescData)
	})
	return file_protos_domain_skill_grpc_proto_rawDescData
}

var file_protos_domain_skill_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_domain_skill_grpc_proto_goTypes = []interface{}{
	(*JobSeekerSkill)(nil), // 0: protos.domain.JobSeekerSkill
}
var file_protos_domain_skill_grpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_domain_skill_grpc_proto_init() }
func file_protos_domain_skill_grpc_proto_init() {
	if File_protos_domain_skill_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_domain_skill_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobSeekerSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_domain_skill_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_domain_skill_grpc_proto_goTypes,
		DependencyIndexes: file_protos_domain_skill_grpc_proto_depIdxs,
		MessageInfos:      file_protos_domain_skill_grpc_proto_msgTypes,
	}.Build()
	File_protos_domain_skill_grpc_proto = out.File
	file_protos_domain_skill_grpc_proto_rawDesc = nil
	file_protos_domain_skill_grpc_proto_goTypes = nil
	file_protos_domain_skill_grpc_proto_depIdxs = nil
}
