// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/error.grpc.proto

package com.wanpng.jobseeker.grpc.domain;

public interface ErrorGrpcOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.ErrorGrpc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
