// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/error.grpc.proto

package com.wanpng.jobseeker.grpc.domain;

public final class ErrorGrpcProtos {
  private ErrorGrpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_ErrorGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_ErrorGrpc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036protos/domain/error.grpc.proto\022\rprotos" +
      ".domain\"*\n\tErrorGrpc\022\014\n\004code\030\001 \001(\005\022\017\n\007me" +
      "ssage\030\002 \001(\tBm\n com.wanpng.jobseeker.grpc" +
      ".domainB\017ErrorGrpcProtosP\001Z6github.com/w" +
      "anpng/job-seekers-profile-grpc/grpc/doma" +
      "inb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_ErrorGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_ErrorGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_ErrorGrpc_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
