// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employment_type.grpc.proto

package com.wanpng.jobseeker.grpc.domain;

public final class JobSeekerEmploymentTypeProtos {
  private JobSeekerEmploymentTypeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_domain_JobSeekerEmploymentType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_domain_JobSeekerEmploymentType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(protos/domain/employment_type.grpc.pro" +
      "to\022\rprotos.domain\"q\n\027JobSeekerEmployment" +
      "Type\022\n\n\002id\030\001 \001(\t\022\025\n\rjob_seeker_id\030\002 \001(\t\022" +
      "\032\n\022employment_type_id\030\003 \001(\005\022\027\n\017employmen" +
      "t_type\030\004 \001(\tB{\n com.wanpng.jobseeker.grp" +
      "c.domainB\035JobSeekerEmploymentTypeProtosP" +
      "\001Z6github.com/wanpng/job-seekers-profile" +
      "-grpc/grpc/domainb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protos_domain_JobSeekerEmploymentType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_domain_JobSeekerEmploymentType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_domain_JobSeekerEmploymentType_descriptor,
        new java.lang.String[] { "Id", "JobSeekerId", "EmploymentTypeId", "EmploymentType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
