// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/jobseeker.grpc.proto

package com.wanpng.jobseeker.grpc.domain;

/**
 * Protobuf type {@code protos.domain.JobseekerGrpc}
 */
public final class JobseekerGrpc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.domain.JobseekerGrpc)
    JobseekerGrpcOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobseekerGrpc.newBuilder() to construct.
  private JobseekerGrpc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobseekerGrpc() {
    id_ = "";
    firstName_ = "";
    lastName_ = "";
    photoUrl_ = "";
    careerLevel_ = "";
    city_ = "";
    province_ = "";
    availability_ = "";
    jobTitle_ = "";
    email_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobseekerGrpc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobseekerGrpc(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lastName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            photoUrl_ = s;
            break;
          }
          case 40: {

            isLandOwner_ = input.readBool();
            break;
          }
          case 48: {

            careerLevelId_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            careerLevel_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            city_ = s;
            break;
          }
          case 72: {

            provinceId_ = input.readInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            province_ = s;
            break;
          }
          case 88: {

            availabilityId_ = input.readInt32();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            availability_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            jobTitle_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.internal_static_protos_domain_JobseekerGrpc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.internal_static_protos_domain_JobseekerGrpc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.class, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object firstName_;
  /**
   * <pre>
   * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
   * </pre>
   *
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
   * </pre>
   *
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastName_;
  /**
   * <pre>
   * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
   * </pre>
   *
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
   * </pre>
   *
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHOTO_URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object photoUrl_;
  /**
   * <pre>
   * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
   * </pre>
   *
   * <code>string photo_url = 4;</code>
   * @return The photoUrl.
   */
  @java.lang.Override
  public java.lang.String getPhotoUrl() {
    java.lang.Object ref = photoUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      photoUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
   * </pre>
   *
   * <code>string photo_url = 4;</code>
   * @return The bytes for photoUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhotoUrlBytes() {
    java.lang.Object ref = photoUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      photoUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_LAND_OWNER_FIELD_NUMBER = 5;
  private boolean isLandOwner_;
  /**
   * <pre>
   * &#64;inject_tag: json:"isLandOwner" gorm:"column:is_land_owner;"
   * </pre>
   *
   * <code>bool is_land_owner = 5;</code>
   * @return The isLandOwner.
   */
  @java.lang.Override
  public boolean getIsLandOwner() {
    return isLandOwner_;
  }

  public static final int CAREER_LEVEL_ID_FIELD_NUMBER = 6;
  private int careerLevelId_;
  /**
   * <pre>
   * &#64;inject_tag: json:"careerLevelId" gorm:"column:career_level_id;"
   * </pre>
   *
   * <code>int32 career_level_id = 6;</code>
   * @return The careerLevelId.
   */
  @java.lang.Override
  public int getCareerLevelId() {
    return careerLevelId_;
  }

  public static final int CAREER_LEVEL_FIELD_NUMBER = 7;
  private volatile java.lang.Object careerLevel_;
  /**
   * <pre>
   * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
   * </pre>
   *
   * <code>string career_level = 7;</code>
   * @return The careerLevel.
   */
  @java.lang.Override
  public java.lang.String getCareerLevel() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      careerLevel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
   * </pre>
   *
   * <code>string career_level = 7;</code>
   * @return The bytes for careerLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCareerLevelBytes() {
    java.lang.Object ref = careerLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      careerLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CITY_FIELD_NUMBER = 8;
  private volatile java.lang.Object city_;
  /**
   * <pre>
   * &#64;inject_tag: json:"city" gorm:"column:city;"
   * </pre>
   *
   * <code>string city = 8;</code>
   * @return The city.
   */
  @java.lang.Override
  public java.lang.String getCity() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      city_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"city" gorm:"column:city;"
   * </pre>
   *
   * <code>string city = 8;</code>
   * @return The bytes for city.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    java.lang.Object ref = city_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      city_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVINCE_ID_FIELD_NUMBER = 9;
  private int provinceId_;
  /**
   * <pre>
   * &#64;inject_tag: json:"provinceId" gorm:"column:province_id;"
   * </pre>
   *
   * <code>int32 province_id = 9;</code>
   * @return The provinceId.
   */
  @java.lang.Override
  public int getProvinceId() {
    return provinceId_;
  }

  public static final int PROVINCE_FIELD_NUMBER = 10;
  private volatile java.lang.Object province_;
  /**
   * <pre>
   * &#64;inject_tag: json:"province" gorm:"column:province;"
   * </pre>
   *
   * <code>string province = 10;</code>
   * @return The province.
   */
  @java.lang.Override
  public java.lang.String getProvince() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      province_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"province" gorm:"column:province;"
   * </pre>
   *
   * <code>string province = 10;</code>
   * @return The bytes for province.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProvinceBytes() {
    java.lang.Object ref = province_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      province_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABILITY_ID_FIELD_NUMBER = 11;
  private int availabilityId_;
  /**
   * <pre>
   * &#64;inject_tag: json:"availabilityId" gorm:"column:availability_id;"
   * </pre>
   *
   * <code>int32 availability_id = 11;</code>
   * @return The availabilityId.
   */
  @java.lang.Override
  public int getAvailabilityId() {
    return availabilityId_;
  }

  public static final int AVAILABILITY_FIELD_NUMBER = 12;
  private volatile java.lang.Object availability_;
  /**
   * <pre>
   * &#64;inject_tag: json:"availability" gorm:"column:availability;"
   * </pre>
   *
   * <code>string availability = 12;</code>
   * @return The availability.
   */
  @java.lang.Override
  public java.lang.String getAvailability() {
    java.lang.Object ref = availability_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      availability_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"availability" gorm:"column:availability;"
   * </pre>
   *
   * <code>string availability = 12;</code>
   * @return The bytes for availability.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAvailabilityBytes() {
    java.lang.Object ref = availability_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      availability_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_TITLE_FIELD_NUMBER = 13;
  private volatile java.lang.Object jobTitle_;
  /**
   * <pre>
   * &#64;inject_tag: json:"jobTitle"
   * </pre>
   *
   * <code>string job_title = 13;</code>
   * @return The jobTitle.
   */
  @java.lang.Override
  public java.lang.String getJobTitle() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jobTitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"jobTitle"
   * </pre>
   *
   * <code>string job_title = 13;</code>
   * @return The bytes for jobTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJobTitleBytes() {
    java.lang.Object ref = jobTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jobTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 14;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   * &#64;inject_tag: json:"email" gorm:"column:email;"
   * </pre>
   *
   * <code>string email = 14;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * &#64;inject_tag: json:"email" gorm:"column:email;"
   * </pre>
   *
   * <code>string email = 14;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(photoUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, photoUrl_);
    }
    if (isLandOwner_ != false) {
      output.writeBool(5, isLandOwner_);
    }
    if (careerLevelId_ != 0) {
      output.writeInt32(6, careerLevelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(careerLevel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, careerLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, city_);
    }
    if (provinceId_ != 0) {
      output.writeInt32(9, provinceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(province_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, province_);
    }
    if (availabilityId_ != 0) {
      output.writeInt32(11, availabilityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(availability_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, availability_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jobTitle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, jobTitle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, email_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(photoUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, photoUrl_);
    }
    if (isLandOwner_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isLandOwner_);
    }
    if (careerLevelId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, careerLevelId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(careerLevel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, careerLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, city_);
    }
    if (provinceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, provinceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(province_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, province_);
    }
    if (availabilityId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, availabilityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(availability_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, availability_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jobTitle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, jobTitle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, email_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobseeker.grpc.domain.JobseekerGrpc)) {
      return super.equals(obj);
    }
    com.wanpng.jobseeker.grpc.domain.JobseekerGrpc other = (com.wanpng.jobseeker.grpc.domain.JobseekerGrpc) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getPhotoUrl()
        .equals(other.getPhotoUrl())) return false;
    if (getIsLandOwner()
        != other.getIsLandOwner()) return false;
    if (getCareerLevelId()
        != other.getCareerLevelId()) return false;
    if (!getCareerLevel()
        .equals(other.getCareerLevel())) return false;
    if (!getCity()
        .equals(other.getCity())) return false;
    if (getProvinceId()
        != other.getProvinceId()) return false;
    if (!getProvince()
        .equals(other.getProvince())) return false;
    if (getAvailabilityId()
        != other.getAvailabilityId()) return false;
    if (!getAvailability()
        .equals(other.getAvailability())) return false;
    if (!getJobTitle()
        .equals(other.getJobTitle())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + PHOTO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPhotoUrl().hashCode();
    hash = (37 * hash) + IS_LAND_OWNER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLandOwner());
    hash = (37 * hash) + CAREER_LEVEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCareerLevelId();
    hash = (37 * hash) + CAREER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getCareerLevel().hashCode();
    hash = (37 * hash) + CITY_FIELD_NUMBER;
    hash = (53 * hash) + getCity().hashCode();
    hash = (37 * hash) + PROVINCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProvinceId();
    hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
    hash = (53 * hash) + getProvince().hashCode();
    hash = (37 * hash) + AVAILABILITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAvailabilityId();
    hash = (37 * hash) + AVAILABILITY_FIELD_NUMBER;
    hash = (53 * hash) + getAvailability().hashCode();
    hash = (37 * hash) + JOB_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getJobTitle().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobseeker.grpc.domain.JobseekerGrpc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.domain.JobseekerGrpc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.domain.JobseekerGrpc)
      com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.internal_static_protos_domain_JobseekerGrpc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.internal_static_protos_domain_JobseekerGrpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.class, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder.class);
    }

    // Construct using com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      firstName_ = "";

      lastName_ = "";

      photoUrl_ = "";

      isLandOwner_ = false;

      careerLevelId_ = 0;

      careerLevel_ = "";

      city_ = "";

      provinceId_ = 0;

      province_ = "";

      availabilityId_ = 0;

      availability_ = "";

      jobTitle_ = "";

      email_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.internal_static_protos_domain_JobseekerGrpc_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc getDefaultInstanceForType() {
      return com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc build() {
      com.wanpng.jobseeker.grpc.domain.JobseekerGrpc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc buildPartial() {
      com.wanpng.jobseeker.grpc.domain.JobseekerGrpc result = new com.wanpng.jobseeker.grpc.domain.JobseekerGrpc(this);
      result.id_ = id_;
      result.firstName_ = firstName_;
      result.lastName_ = lastName_;
      result.photoUrl_ = photoUrl_;
      result.isLandOwner_ = isLandOwner_;
      result.careerLevelId_ = careerLevelId_;
      result.careerLevel_ = careerLevel_;
      result.city_ = city_;
      result.provinceId_ = provinceId_;
      result.province_ = province_;
      result.availabilityId_ = availabilityId_;
      result.availability_ = availability_;
      result.jobTitle_ = jobTitle_;
      result.email_ = email_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobseeker.grpc.domain.JobseekerGrpc) {
        return mergeFrom((com.wanpng.jobseeker.grpc.domain.JobseekerGrpc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobseeker.grpc.domain.JobseekerGrpc other) {
      if (other == com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (!other.getPhotoUrl().isEmpty()) {
        photoUrl_ = other.photoUrl_;
        onChanged();
      }
      if (other.getIsLandOwner() != false) {
        setIsLandOwner(other.getIsLandOwner());
      }
      if (other.getCareerLevelId() != 0) {
        setCareerLevelId(other.getCareerLevelId());
      }
      if (!other.getCareerLevel().isEmpty()) {
        careerLevel_ = other.careerLevel_;
        onChanged();
      }
      if (!other.getCity().isEmpty()) {
        city_ = other.city_;
        onChanged();
      }
      if (other.getProvinceId() != 0) {
        setProvinceId(other.getProvinceId());
      }
      if (!other.getProvince().isEmpty()) {
        province_ = other.province_;
        onChanged();
      }
      if (other.getAvailabilityId() != 0) {
        setAvailabilityId(other.getAvailabilityId());
      }
      if (!other.getAvailability().isEmpty()) {
        availability_ = other.availability_;
        onChanged();
      }
      if (!other.getJobTitle().isEmpty()) {
        jobTitle_ = other.jobTitle_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobseeker.grpc.domain.JobseekerGrpc parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobseeker.grpc.domain.JobseekerGrpc) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"id" gorm:"column:job_seeker_id;primary_key;"
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"firstName" gorm:"column:first_name;"
     * </pre>
     *
     * <code>string first_name = 2;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"lastName" gorm:"column:last_name;"
     * </pre>
     *
     * <code>string last_name = 3;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object photoUrl_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
     * </pre>
     *
     * <code>string photo_url = 4;</code>
     * @return The photoUrl.
     */
    public java.lang.String getPhotoUrl() {
      java.lang.Object ref = photoUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        photoUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
     * </pre>
     *
     * <code>string photo_url = 4;</code>
     * @return The bytes for photoUrl.
     */
    public com.google.protobuf.ByteString
        getPhotoUrlBytes() {
      java.lang.Object ref = photoUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        photoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
     * </pre>
     *
     * <code>string photo_url = 4;</code>
     * @param value The photoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPhotoUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photoUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
     * </pre>
     *
     * <code>string photo_url = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhotoUrl() {
      
      photoUrl_ = getDefaultInstance().getPhotoUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"photoUrl" gorm:"column:photo_url;"
     * </pre>
     *
     * <code>string photo_url = 4;</code>
     * @param value The bytes for photoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setPhotoUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      photoUrl_ = value;
      onChanged();
      return this;
    }

    private boolean isLandOwner_ ;
    /**
     * <pre>
     * &#64;inject_tag: json:"isLandOwner" gorm:"column:is_land_owner;"
     * </pre>
     *
     * <code>bool is_land_owner = 5;</code>
     * @return The isLandOwner.
     */
    @java.lang.Override
    public boolean getIsLandOwner() {
      return isLandOwner_;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"isLandOwner" gorm:"column:is_land_owner;"
     * </pre>
     *
     * <code>bool is_land_owner = 5;</code>
     * @param value The isLandOwner to set.
     * @return This builder for chaining.
     */
    public Builder setIsLandOwner(boolean value) {
      
      isLandOwner_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"isLandOwner" gorm:"column:is_land_owner;"
     * </pre>
     *
     * <code>bool is_land_owner = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLandOwner() {
      
      isLandOwner_ = false;
      onChanged();
      return this;
    }

    private int careerLevelId_ ;
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevelId" gorm:"column:career_level_id;"
     * </pre>
     *
     * <code>int32 career_level_id = 6;</code>
     * @return The careerLevelId.
     */
    @java.lang.Override
    public int getCareerLevelId() {
      return careerLevelId_;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevelId" gorm:"column:career_level_id;"
     * </pre>
     *
     * <code>int32 career_level_id = 6;</code>
     * @param value The careerLevelId to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevelId(int value) {
      
      careerLevelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevelId" gorm:"column:career_level_id;"
     * </pre>
     *
     * <code>int32 career_level_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCareerLevelId() {
      
      careerLevelId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object careerLevel_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
     * </pre>
     *
     * <code>string career_level = 7;</code>
     * @return The careerLevel.
     */
    public java.lang.String getCareerLevel() {
      java.lang.Object ref = careerLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        careerLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
     * </pre>
     *
     * <code>string career_level = 7;</code>
     * @return The bytes for careerLevel.
     */
    public com.google.protobuf.ByteString
        getCareerLevelBytes() {
      java.lang.Object ref = careerLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        careerLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
     * </pre>
     *
     * <code>string career_level = 7;</code>
     * @param value The careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      careerLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
     * </pre>
     *
     * <code>string career_level = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCareerLevel() {
      
      careerLevel_ = getDefaultInstance().getCareerLevel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"careerLevel" gorm:"column:career_level;"
     * </pre>
     *
     * <code>string career_level = 7;</code>
     * @param value The bytes for careerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setCareerLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      careerLevel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object city_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"city" gorm:"column:city;"
     * </pre>
     *
     * <code>string city = 8;</code>
     * @return The city.
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"city" gorm:"column:city;"
     * </pre>
     *
     * <code>string city = 8;</code>
     * @return The bytes for city.
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"city" gorm:"column:city;"
     * </pre>
     *
     * <code>string city = 8;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      city_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"city" gorm:"column:city;"
     * </pre>
     *
     * <code>string city = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      
      city_ = getDefaultInstance().getCity();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"city" gorm:"column:city;"
     * </pre>
     *
     * <code>string city = 8;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      city_ = value;
      onChanged();
      return this;
    }

    private int provinceId_ ;
    /**
     * <pre>
     * &#64;inject_tag: json:"provinceId" gorm:"column:province_id;"
     * </pre>
     *
     * <code>int32 province_id = 9;</code>
     * @return The provinceId.
     */
    @java.lang.Override
    public int getProvinceId() {
      return provinceId_;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"provinceId" gorm:"column:province_id;"
     * </pre>
     *
     * <code>int32 province_id = 9;</code>
     * @param value The provinceId to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceId(int value) {
      
      provinceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"provinceId" gorm:"column:province_id;"
     * </pre>
     *
     * <code>int32 province_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvinceId() {
      
      provinceId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object province_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"province" gorm:"column:province;"
     * </pre>
     *
     * <code>string province = 10;</code>
     * @return The province.
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"province" gorm:"column:province;"
     * </pre>
     *
     * <code>string province = 10;</code>
     * @return The bytes for province.
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"province" gorm:"column:province;"
     * </pre>
     *
     * <code>string province = 10;</code>
     * @param value The province to set.
     * @return This builder for chaining.
     */
    public Builder setProvince(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      province_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"province" gorm:"column:province;"
     * </pre>
     *
     * <code>string province = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearProvince() {
      
      province_ = getDefaultInstance().getProvince();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"province" gorm:"column:province;"
     * </pre>
     *
     * <code>string province = 10;</code>
     * @param value The bytes for province to set.
     * @return This builder for chaining.
     */
    public Builder setProvinceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      province_ = value;
      onChanged();
      return this;
    }

    private int availabilityId_ ;
    /**
     * <pre>
     * &#64;inject_tag: json:"availabilityId" gorm:"column:availability_id;"
     * </pre>
     *
     * <code>int32 availability_id = 11;</code>
     * @return The availabilityId.
     */
    @java.lang.Override
    public int getAvailabilityId() {
      return availabilityId_;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"availabilityId" gorm:"column:availability_id;"
     * </pre>
     *
     * <code>int32 availability_id = 11;</code>
     * @param value The availabilityId to set.
     * @return This builder for chaining.
     */
    public Builder setAvailabilityId(int value) {
      
      availabilityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"availabilityId" gorm:"column:availability_id;"
     * </pre>
     *
     * <code>int32 availability_id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailabilityId() {
      
      availabilityId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object availability_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"availability" gorm:"column:availability;"
     * </pre>
     *
     * <code>string availability = 12;</code>
     * @return The availability.
     */
    public java.lang.String getAvailability() {
      java.lang.Object ref = availability_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        availability_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"availability" gorm:"column:availability;"
     * </pre>
     *
     * <code>string availability = 12;</code>
     * @return The bytes for availability.
     */
    public com.google.protobuf.ByteString
        getAvailabilityBytes() {
      java.lang.Object ref = availability_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        availability_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"availability" gorm:"column:availability;"
     * </pre>
     *
     * <code>string availability = 12;</code>
     * @param value The availability to set.
     * @return This builder for chaining.
     */
    public Builder setAvailability(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      availability_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"availability" gorm:"column:availability;"
     * </pre>
     *
     * <code>string availability = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailability() {
      
      availability_ = getDefaultInstance().getAvailability();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"availability" gorm:"column:availability;"
     * </pre>
     *
     * <code>string availability = 12;</code>
     * @param value The bytes for availability to set.
     * @return This builder for chaining.
     */
    public Builder setAvailabilityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      availability_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jobTitle_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"jobTitle"
     * </pre>
     *
     * <code>string job_title = 13;</code>
     * @return The jobTitle.
     */
    public java.lang.String getJobTitle() {
      java.lang.Object ref = jobTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"jobTitle"
     * </pre>
     *
     * <code>string job_title = 13;</code>
     * @return The bytes for jobTitle.
     */
    public com.google.protobuf.ByteString
        getJobTitleBytes() {
      java.lang.Object ref = jobTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"jobTitle"
     * </pre>
     *
     * <code>string job_title = 13;</code>
     * @param value The jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobTitle_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"jobTitle"
     * </pre>
     *
     * <code>string job_title = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobTitle() {
      
      jobTitle_ = getDefaultInstance().getJobTitle();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"jobTitle"
     * </pre>
     *
     * <code>string job_title = 13;</code>
     * @param value The bytes for jobTitle to set.
     * @return This builder for chaining.
     */
    public Builder setJobTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobTitle_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     * &#64;inject_tag: json:"email" gorm:"column:email;"
     * </pre>
     *
     * <code>string email = 14;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"email" gorm:"column:email;"
     * </pre>
     *
     * <code>string email = 14;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"email" gorm:"column:email;"
     * </pre>
     *
     * <code>string email = 14;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"email" gorm:"column:email;"
     * </pre>
     *
     * <code>string email = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * &#64;inject_tag: json:"email" gorm:"column:email;"
     * </pre>
     *
     * <code>string email = 14;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.domain.JobseekerGrpc)
  }

  // @@protoc_insertion_point(class_scope:protos.domain.JobseekerGrpc)
  private static final com.wanpng.jobseeker.grpc.domain.JobseekerGrpc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobseeker.grpc.domain.JobseekerGrpc();
  }

  public static com.wanpng.jobseeker.grpc.domain.JobseekerGrpc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobseekerGrpc>
      PARSER = new com.google.protobuf.AbstractParser<JobseekerGrpc>() {
    @java.lang.Override
    public JobseekerGrpc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobseekerGrpc(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobseekerGrpc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobseekerGrpc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

