// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/employment_type.grpc.proto

package com.wanpng.jobseeker.grpc.domain;

public interface JobSeekerEmploymentTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.JobSeekerEmploymentType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;inject_tag: json:"id" gorm:"column:job_seeker_employment_type_id;primary_key;"
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * &#64;inject_tag: json:"id" gorm:"column:job_seeker_employment_type_id;primary_key;"
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * &#64;inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
   * </pre>
   *
   * <code>string job_seeker_id = 2;</code>
   * @return The jobSeekerId.
   */
  java.lang.String getJobSeekerId();
  /**
   * <pre>
   * &#64;inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
   * </pre>
   *
   * <code>string job_seeker_id = 2;</code>
   * @return The bytes for jobSeekerId.
   */
  com.google.protobuf.ByteString
      getJobSeekerIdBytes();

  /**
   * <pre>
   * &#64;inject_tag: json:"employmentTypeId" gorm:"column:employment_type_id;"
   * </pre>
   *
   * <code>int32 employment_type_id = 3;</code>
   * @return The employmentTypeId.
   */
  int getEmploymentTypeId();

  /**
   * <pre>
   * &#64;inject_tag: json:"employmentType" gorm:"column:employment_type;"
   * </pre>
   *
   * <code>string employment_type = 4;</code>
   * @return The employmentType.
   */
  java.lang.String getEmploymentType();
  /**
   * <pre>
   * &#64;inject_tag: json:"employmentType" gorm:"column:employment_type;"
   * </pre>
   *
   * <code>string employment_type = 4;</code>
   * @return The bytes for employmentType.
   */
  com.google.protobuf.ByteString
      getEmploymentTypeBytes();
}
