// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/domain/skill.grpc.proto

package com.wanpng.jobseeker.grpc.domain;

public interface JobSeekerSkillOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.domain.JobSeekerSkill)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * &#64;inject_tag: json:"id" gorm:"column:job_seeker_skill_id;primary_key;"
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * &#64;inject_tag: json:"id" gorm:"column:job_seeker_skill_id;primary_key;"
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * &#64;inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
   * </pre>
   *
   * <code>string job_seeker_id = 2;</code>
   * @return The jobSeekerId.
   */
  java.lang.String getJobSeekerId();
  /**
   * <pre>
   * &#64;inject_tag: json:"jobSeekerId" gorm:"column:job_seeker_id;"
   * </pre>
   *
   * <code>string job_seeker_id = 2;</code>
   * @return The bytes for jobSeekerId.
   */
  com.google.protobuf.ByteString
      getJobSeekerIdBytes();

  /**
   * <pre>
   * &#64;inject_tag: json:"skillId" gorm:"column:skill_id;"
   * </pre>
   *
   * <code>string skill_id = 3;</code>
   * @return The skillId.
   */
  java.lang.String getSkillId();
  /**
   * <pre>
   * &#64;inject_tag: json:"skillId" gorm:"column:skill_id;"
   * </pre>
   *
   * <code>string skill_id = 3;</code>
   * @return The bytes for skillId.
   */
  com.google.protobuf.ByteString
      getSkillIdBytes();

  /**
   * <pre>
   * &#64;inject_tag: json:"skill" gorm:"column:skill;"
   * </pre>
   *
   * <code>string skill = 4;</code>
   * @return The skill.
   */
  java.lang.String getSkill();
  /**
   * <pre>
   * &#64;inject_tag: json:"skill" gorm:"column:skill;"
   * </pre>
   *
   * <code>string skill = 4;</code>
   * @return The bytes for skill.
   */
  com.google.protobuf.ByteString
      getSkillBytes();

  /**
   * <pre>
   * &#64;inject_tag: json:"levelId" gorm:"column:level_id;"
   * </pre>
   *
   * <code>int32 level_id = 5;</code>
   * @return The levelId.
   */
  int getLevelId();

  /**
   * <pre>
   * &#64;inject_tag: json:"level" gorm:"column:level;"
   * </pre>
   *
   * <code>string level = 6;</code>
   * @return The level.
   */
  java.lang.String getLevel();
  /**
   * <pre>
   * &#64;inject_tag: json:"level" gorm:"column:level;"
   * </pre>
   *
   * <code>string level = 6;</code>
   * @return The bytes for level.
   */
  com.google.protobuf.ByteString
      getLevelBytes();
}
