// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

/**
 * Protobuf enum {@code protos.service.ApplicationStatus}
 */
public enum ApplicationStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>APPLIED = 0;</code>
   */
  APPLIED(0),
  /**
   * <code>REVIEWING = 1;</code>
   */
  REVIEWING(1),
  /**
   * <code>INTERVIEWING = 2;</code>
   */
  INTERVIEWING(2),
  /**
   * <code>SHORTLIST = 3;</code>
   */
  SHORTLIST(3),
  /**
   * <code>OFFERING = 4;</code>
   */
  OFFERING(4),
  /**
   * <code>HIRED = 5;</code>
   */
  HIRED(5),
  /**
   * <code>NOT_SELECTED = 6;</code>
   */
  NOT_SELECTED(6),
  /**
   * <code>WITHDRAW = 7;</code>
   */
  WITHDRAW(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>APPLIED = 0;</code>
   */
  public static final int APPLIED_VALUE = 0;
  /**
   * <code>REVIEWING = 1;</code>
   */
  public static final int REVIEWING_VALUE = 1;
  /**
   * <code>INTERVIEWING = 2;</code>
   */
  public static final int INTERVIEWING_VALUE = 2;
  /**
   * <code>SHORTLIST = 3;</code>
   */
  public static final int SHORTLIST_VALUE = 3;
  /**
   * <code>OFFERING = 4;</code>
   */
  public static final int OFFERING_VALUE = 4;
  /**
   * <code>HIRED = 5;</code>
   */
  public static final int HIRED_VALUE = 5;
  /**
   * <code>NOT_SELECTED = 6;</code>
   */
  public static final int NOT_SELECTED_VALUE = 6;
  /**
   * <code>WITHDRAW = 7;</code>
   */
  public static final int WITHDRAW_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ApplicationStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ApplicationStatus forNumber(int value) {
    switch (value) {
      case 0: return APPLIED;
      case 1: return REVIEWING;
      case 2: return INTERVIEWING;
      case 3: return SHORTLIST;
      case 4: return OFFERING;
      case 5: return HIRED;
      case 6: return NOT_SELECTED;
      case 7: return WITHDRAW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ApplicationStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ApplicationStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ApplicationStatus>() {
          public ApplicationStatus findValueByNumber(int number) {
            return ApplicationStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final ApplicationStatus[] VALUES = values();

  public static ApplicationStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ApplicationStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protos.service.ApplicationStatus)
}

