// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

public interface GetEmploymentTypesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetEmploymentTypesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string candidateId = 1;</code>
   * @return The candidateId.
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidateId = 1;</code>
   * @return The bytes for candidateId.
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();
}
