// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

public interface GetJobSeekerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetJobSeekerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protos.domain.JobseekerGrpc jobseeker = 1;</code>
   * @return Whether the jobseeker field is set.
   */
  boolean hasJobseeker();
  /**
   * <code>.protos.domain.JobseekerGrpc jobseeker = 1;</code>
   * @return The jobseeker.
   */
  com.wanpng.jobseeker.grpc.domain.JobseekerGrpc getJobseeker();
  /**
   * <code>.protos.domain.JobseekerGrpc jobseeker = 1;</code>
   */
  com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder getJobseekerOrBuilder();
}
