// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

/**
 * Protobuf type {@code protos.service.GetJobseekersResponse}
 */
public final class GetJobseekersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.GetJobseekersResponse)
    GetJobseekersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetJobseekersResponse.newBuilder() to construct.
  private GetJobseekersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetJobseekersResponse() {
    jobseekers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetJobseekersResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetJobseekersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobseekers_ = new java.util.ArrayList<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobseekers_.add(
                input.readMessage(com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobseekers_ = java.util.Collections.unmodifiableList(jobseekers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetJobseekersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetJobseekersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.class, com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.Builder.class);
  }

  public static final int JOBSEEKERS_FIELD_NUMBER = 1;
  private java.util.List<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc> jobseekers_;
  /**
   * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc> getJobseekersList() {
    return jobseekers_;
  }
  /**
   * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder> 
      getJobseekersOrBuilderList() {
    return jobseekers_;
  }
  /**
   * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
   */
  @java.lang.Override
  public int getJobseekersCount() {
    return jobseekers_.size();
  }
  /**
   * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc getJobseekers(int index) {
    return jobseekers_.get(index);
  }
  /**
   * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder getJobseekersOrBuilder(
      int index) {
    return jobseekers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobseekers_.size(); i++) {
      output.writeMessage(1, jobseekers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobseekers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobseekers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobseeker.grpc.service.GetJobseekersResponse)) {
      return super.equals(obj);
    }
    com.wanpng.jobseeker.grpc.service.GetJobseekersResponse other = (com.wanpng.jobseeker.grpc.service.GetJobseekersResponse) obj;

    if (!getJobseekersList()
        .equals(other.getJobseekersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobseekersCount() > 0) {
      hash = (37 * hash) + JOBSEEKERS_FIELD_NUMBER;
      hash = (53 * hash) + getJobseekersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobseeker.grpc.service.GetJobseekersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.GetJobseekersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.GetJobseekersResponse)
      com.wanpng.jobseeker.grpc.service.GetJobseekersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetJobseekersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetJobseekersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.class, com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.Builder.class);
    }

    // Construct using com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobseekersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobseekersBuilder_ == null) {
        jobseekers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobseekersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetJobseekersResponse_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.service.GetJobseekersResponse getDefaultInstanceForType() {
      return com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.service.GetJobseekersResponse build() {
      com.wanpng.jobseeker.grpc.service.GetJobseekersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.service.GetJobseekersResponse buildPartial() {
      com.wanpng.jobseeker.grpc.service.GetJobseekersResponse result = new com.wanpng.jobseeker.grpc.service.GetJobseekersResponse(this);
      int from_bitField0_ = bitField0_;
      if (jobseekersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobseekers_ = java.util.Collections.unmodifiableList(jobseekers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobseekers_ = jobseekers_;
      } else {
        result.jobseekers_ = jobseekersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobseeker.grpc.service.GetJobseekersResponse) {
        return mergeFrom((com.wanpng.jobseeker.grpc.service.GetJobseekersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobseeker.grpc.service.GetJobseekersResponse other) {
      if (other == com.wanpng.jobseeker.grpc.service.GetJobseekersResponse.getDefaultInstance()) return this;
      if (jobseekersBuilder_ == null) {
        if (!other.jobseekers_.isEmpty()) {
          if (jobseekers_.isEmpty()) {
            jobseekers_ = other.jobseekers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobseekersIsMutable();
            jobseekers_.addAll(other.jobseekers_);
          }
          onChanged();
        }
      } else {
        if (!other.jobseekers_.isEmpty()) {
          if (jobseekersBuilder_.isEmpty()) {
            jobseekersBuilder_.dispose();
            jobseekersBuilder_ = null;
            jobseekers_ = other.jobseekers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobseekersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobseekersFieldBuilder() : null;
          } else {
            jobseekersBuilder_.addAllMessages(other.jobseekers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobseeker.grpc.service.GetJobseekersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobseeker.grpc.service.GetJobseekersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc> jobseekers_ =
      java.util.Collections.emptyList();
    private void ensureJobseekersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobseekers_ = new java.util.ArrayList<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc>(jobseekers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.jobseeker.grpc.domain.JobseekerGrpc, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder, com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder> jobseekersBuilder_;

    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public java.util.List<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc> getJobseekersList() {
      if (jobseekersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobseekers_);
      } else {
        return jobseekersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public int getJobseekersCount() {
      if (jobseekersBuilder_ == null) {
        return jobseekers_.size();
      } else {
        return jobseekersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc getJobseekers(int index) {
      if (jobseekersBuilder_ == null) {
        return jobseekers_.get(index);
      } else {
        return jobseekersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder setJobseekers(
        int index, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc value) {
      if (jobseekersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobseekersIsMutable();
        jobseekers_.set(index, value);
        onChanged();
      } else {
        jobseekersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder setJobseekers(
        int index, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder builderForValue) {
      if (jobseekersBuilder_ == null) {
        ensureJobseekersIsMutable();
        jobseekers_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobseekersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder addJobseekers(com.wanpng.jobseeker.grpc.domain.JobseekerGrpc value) {
      if (jobseekersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobseekersIsMutable();
        jobseekers_.add(value);
        onChanged();
      } else {
        jobseekersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder addJobseekers(
        int index, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc value) {
      if (jobseekersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobseekersIsMutable();
        jobseekers_.add(index, value);
        onChanged();
      } else {
        jobseekersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder addJobseekers(
        com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder builderForValue) {
      if (jobseekersBuilder_ == null) {
        ensureJobseekersIsMutable();
        jobseekers_.add(builderForValue.build());
        onChanged();
      } else {
        jobseekersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder addJobseekers(
        int index, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder builderForValue) {
      if (jobseekersBuilder_ == null) {
        ensureJobseekersIsMutable();
        jobseekers_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobseekersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder addAllJobseekers(
        java.lang.Iterable<? extends com.wanpng.jobseeker.grpc.domain.JobseekerGrpc> values) {
      if (jobseekersBuilder_ == null) {
        ensureJobseekersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobseekers_);
        onChanged();
      } else {
        jobseekersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder clearJobseekers() {
      if (jobseekersBuilder_ == null) {
        jobseekers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobseekersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public Builder removeJobseekers(int index) {
      if (jobseekersBuilder_ == null) {
        ensureJobseekersIsMutable();
        jobseekers_.remove(index);
        onChanged();
      } else {
        jobseekersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder getJobseekersBuilder(
        int index) {
      return getJobseekersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder getJobseekersOrBuilder(
        int index) {
      if (jobseekersBuilder_ == null) {
        return jobseekers_.get(index);  } else {
        return jobseekersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public java.util.List<? extends com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder> 
         getJobseekersOrBuilderList() {
      if (jobseekersBuilder_ != null) {
        return jobseekersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobseekers_);
      }
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder addJobseekersBuilder() {
      return getJobseekersFieldBuilder().addBuilder(
          com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder addJobseekersBuilder(
        int index) {
      return getJobseekersFieldBuilder().addBuilder(
          index, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobseekerGrpc jobseekers = 1;</code>
     */
    public java.util.List<com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder> 
         getJobseekersBuilderList() {
      return getJobseekersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.jobseeker.grpc.domain.JobseekerGrpc, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder, com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder> 
        getJobseekersFieldBuilder() {
      if (jobseekersBuilder_ == null) {
        jobseekersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.jobseeker.grpc.domain.JobseekerGrpc, com.wanpng.jobseeker.grpc.domain.JobseekerGrpc.Builder, com.wanpng.jobseeker.grpc.domain.JobseekerGrpcOrBuilder>(
                jobseekers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobseekers_ = null;
      }
      return jobseekersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.GetJobseekersResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.service.GetJobseekersResponse)
  private static final com.wanpng.jobseeker.grpc.service.GetJobseekersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobseeker.grpc.service.GetJobseekersResponse();
  }

  public static com.wanpng.jobseeker.grpc.service.GetJobseekersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetJobseekersResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetJobseekersResponse>() {
    @java.lang.Override
    public GetJobseekersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetJobseekersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetJobseekersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetJobseekersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobseeker.grpc.service.GetJobseekersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

