// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

public interface GetSkillsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.service.GetSkillsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  java.util.List<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill> 
      getSkillsList();
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  com.wanpng.jobseeker.grpc.domain.JobSeekerSkill getSkills(int index);
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  int getSkillsCount();
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  java.util.List<? extends com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder> 
      getSkillsOrBuilderList();
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder getSkillsOrBuilder(
      int index);
}
