// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

/**
 * Protobuf type {@code protos.service.GetSkillsResponse}
 */
public final class GetSkillsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protos.service.GetSkillsResponse)
    GetSkillsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSkillsResponse.newBuilder() to construct.
  private GetSkillsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSkillsResponse() {
    skills_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSkillsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetSkillsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              skills_ = new java.util.ArrayList<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill>();
              mutable_bitField0_ |= 0x00000001;
            }
            skills_.add(
                input.readMessage(com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        skills_ = java.util.Collections.unmodifiableList(skills_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetSkillsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetSkillsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wanpng.jobseeker.grpc.service.GetSkillsResponse.class, com.wanpng.jobseeker.grpc.service.GetSkillsResponse.Builder.class);
  }

  public static final int SKILLS_FIELD_NUMBER = 1;
  private java.util.List<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill> skills_;
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill> getSkillsList() {
    return skills_;
  }
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder> 
      getSkillsOrBuilderList() {
    return skills_;
  }
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  @java.lang.Override
  public int getSkillsCount() {
    return skills_.size();
  }
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.jobseeker.grpc.domain.JobSeekerSkill getSkills(int index) {
    return skills_.get(index);
  }
  /**
   * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
   */
  @java.lang.Override
  public com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder getSkillsOrBuilder(
      int index) {
    return skills_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < skills_.size(); i++) {
      output.writeMessage(1, skills_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < skills_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, skills_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wanpng.jobseeker.grpc.service.GetSkillsResponse)) {
      return super.equals(obj);
    }
    com.wanpng.jobseeker.grpc.service.GetSkillsResponse other = (com.wanpng.jobseeker.grpc.service.GetSkillsResponse) obj;

    if (!getSkillsList()
        .equals(other.getSkillsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSkillsCount() > 0) {
      hash = (37 * hash) + SKILLS_FIELD_NUMBER;
      hash = (53 * hash) + getSkillsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wanpng.jobseeker.grpc.service.GetSkillsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protos.service.GetSkillsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protos.service.GetSkillsResponse)
      com.wanpng.jobseeker.grpc.service.GetSkillsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetSkillsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetSkillsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wanpng.jobseeker.grpc.service.GetSkillsResponse.class, com.wanpng.jobseeker.grpc.service.GetSkillsResponse.Builder.class);
    }

    // Construct using com.wanpng.jobseeker.grpc.service.GetSkillsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSkillsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (skillsBuilder_ == null) {
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        skillsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wanpng.jobseeker.grpc.service.JobseeekerServiceProtos.internal_static_protos_service_GetSkillsResponse_descriptor;
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.service.GetSkillsResponse getDefaultInstanceForType() {
      return com.wanpng.jobseeker.grpc.service.GetSkillsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.service.GetSkillsResponse build() {
      com.wanpng.jobseeker.grpc.service.GetSkillsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wanpng.jobseeker.grpc.service.GetSkillsResponse buildPartial() {
      com.wanpng.jobseeker.grpc.service.GetSkillsResponse result = new com.wanpng.jobseeker.grpc.service.GetSkillsResponse(this);
      int from_bitField0_ = bitField0_;
      if (skillsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skills_ = skills_;
      } else {
        result.skills_ = skillsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wanpng.jobseeker.grpc.service.GetSkillsResponse) {
        return mergeFrom((com.wanpng.jobseeker.grpc.service.GetSkillsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wanpng.jobseeker.grpc.service.GetSkillsResponse other) {
      if (other == com.wanpng.jobseeker.grpc.service.GetSkillsResponse.getDefaultInstance()) return this;
      if (skillsBuilder_ == null) {
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
      } else {
        if (!other.skills_.isEmpty()) {
          if (skillsBuilder_.isEmpty()) {
            skillsBuilder_.dispose();
            skillsBuilder_ = null;
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
            skillsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSkillsFieldBuilder() : null;
          } else {
            skillsBuilder_.addAllMessages(other.skills_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wanpng.jobseeker.grpc.service.GetSkillsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wanpng.jobseeker.grpc.service.GetSkillsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill> skills_ =
      java.util.Collections.emptyList();
    private void ensureSkillsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skills_ = new java.util.ArrayList<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill>(skills_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.jobseeker.grpc.domain.JobSeekerSkill, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder, com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder> skillsBuilder_;

    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public java.util.List<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill> getSkillsList() {
      if (skillsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(skills_);
      } else {
        return skillsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public int getSkillsCount() {
      if (skillsBuilder_ == null) {
        return skills_.size();
      } else {
        return skillsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobSeekerSkill getSkills(int index) {
      if (skillsBuilder_ == null) {
        return skills_.get(index);
      } else {
        return skillsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder setSkills(
        int index, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill value) {
      if (skillsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
      } else {
        skillsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder setSkills(
        int index, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder builderForValue) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.set(index, builderForValue.build());
        onChanged();
      } else {
        skillsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder addSkills(com.wanpng.jobseeker.grpc.domain.JobSeekerSkill value) {
      if (skillsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
      } else {
        skillsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder addSkills(
        int index, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill value) {
      if (skillsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.add(index, value);
        onChanged();
      } else {
        skillsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder addSkills(
        com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder builderForValue) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.add(builderForValue.build());
        onChanged();
      } else {
        skillsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder addSkills(
        int index, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder builderForValue) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.add(index, builderForValue.build());
        onChanged();
      } else {
        skillsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder addAllSkills(
        java.lang.Iterable<? extends com.wanpng.jobseeker.grpc.domain.JobSeekerSkill> values) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skills_);
        onChanged();
      } else {
        skillsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder clearSkills() {
      if (skillsBuilder_ == null) {
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        skillsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public Builder removeSkills(int index) {
      if (skillsBuilder_ == null) {
        ensureSkillsIsMutable();
        skills_.remove(index);
        onChanged();
      } else {
        skillsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder getSkillsBuilder(
        int index) {
      return getSkillsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder getSkillsOrBuilder(
        int index) {
      if (skillsBuilder_ == null) {
        return skills_.get(index);  } else {
        return skillsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public java.util.List<? extends com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder> 
         getSkillsOrBuilderList() {
      if (skillsBuilder_ != null) {
        return skillsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(skills_);
      }
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder addSkillsBuilder() {
      return getSkillsFieldBuilder().addBuilder(
          com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder addSkillsBuilder(
        int index) {
      return getSkillsFieldBuilder().addBuilder(
          index, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.getDefaultInstance());
    }
    /**
     * <code>repeated .protos.domain.JobSeekerSkill skills = 1;</code>
     */
    public java.util.List<com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder> 
         getSkillsBuilderList() {
      return getSkillsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wanpng.jobseeker.grpc.domain.JobSeekerSkill, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder, com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder> 
        getSkillsFieldBuilder() {
      if (skillsBuilder_ == null) {
        skillsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wanpng.jobseeker.grpc.domain.JobSeekerSkill, com.wanpng.jobseeker.grpc.domain.JobSeekerSkill.Builder, com.wanpng.jobseeker.grpc.domain.JobSeekerSkillOrBuilder>(
                skills_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        skills_ = null;
      }
      return skillsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protos.service.GetSkillsResponse)
  }

  // @@protoc_insertion_point(class_scope:protos.service.GetSkillsResponse)
  private static final com.wanpng.jobseeker.grpc.service.GetSkillsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wanpng.jobseeker.grpc.service.GetSkillsResponse();
  }

  public static com.wanpng.jobseeker.grpc.service.GetSkillsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSkillsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSkillsResponse>() {
    @java.lang.Override
    public GetSkillsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetSkillsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetSkillsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSkillsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wanpng.jobseeker.grpc.service.GetSkillsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

