// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/jobseeker_service.grpc.proto

package com.wanpng.jobseeker.grpc.service;

public final class JobseeekerServiceProtos {
  private JobseeekerServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetJobSeekerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetJobSeekerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetJobSeekerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetJobSeekerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetJobseekersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetJobseekersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetJobseekersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetJobseekersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetSkillsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetSkillsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetSkillsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetSkillsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetEmploymentTypesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetEmploymentTypesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_GetEmploymentTypesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_GetEmploymentTypesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SearchJobSeekerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SearchJobSeekerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_service_SearchJobSeekerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_service_SearchJobSeekerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+protos/service/jobseeker_service.grpc." +
      "proto\022\016protos.service\032\"protos/domain/job" +
      "seeker.grpc.proto\032\036protos/domain/skill.g" +
      "rpc.proto\032(protos/domain/employment_type" +
      ".grpc.proto\"+\n\023GetJobSeekerRequest\022\024\n\014jo" +
      "bseeker_id\030\001 \001(\t\"G\n\024GetJobSeekerResponse" +
      "\022/\n\tjobseeker\030\001 \001(\0132\034.protos.domain.Jobs" +
      "eekerGrpc\"l\n\024GetJobseekersRequest\022=\n\022app" +
      "lication_status\030\001 \001(\0162!.protos.service.A" +
      "pplicationStatus\022\025\n\rjobseeker_ids\030\002 \003(\t\"" +
      "I\n\025GetJobseekersResponse\0220\n\njobseekers\030\001" +
      " \003(\0132\034.protos.domain.JobseekerGrpc\"\'\n\020Ge" +
      "tSkillsRequest\022\023\n\013candidateId\030\001 \001(\t\"B\n\021G" +
      "etSkillsResponse\022-\n\006skills\030\001 \003(\0132\035.proto" +
      "s.domain.JobSeekerSkill\"0\n\031GetEmployment" +
      "TypesRequest\022\023\n\013candidateId\030\001 \001(\t\"]\n\032Get" +
      "EmploymentTypesResponse\022?\n\017employmentTyp" +
      "es\030\001 \003(\0132&.protos.domain.JobSeekerEmploy" +
      "mentType\"@\n\026SearchJobSeekerRequest\022\025\n\rjo" +
      "bseeker_ids\030\001 \003(\t\022\017\n\007keyword\030\002 \001(\t\"0\n\027Se" +
      "archJobSeekerResponse\022\025\n\rjobseeker_ids\030\001" +
      " \003(\t*\211\001\n\021ApplicationStatus\022\013\n\007APPLIED\020\000\022" +
      "\r\n\tREVIEWING\020\001\022\020\n\014INTERVIEWING\020\002\022\r\n\tSHOR" +
      "TLIST\020\003\022\014\n\010OFFERING\020\004\022\t\n\005HIRED\020\005\022\020\n\014NOT_" +
      "SELECTED\020\006\022\014\n\010WITHDRAW\020\0072\357\003\n\021JobseeekerS" +
      "ervice\022\\\n\rGetJobseekers\022$.protos.service" +
      ".GetJobseekersRequest\032%.protos.service.G" +
      "etJobseekersResponse\022Y\n\014GetJobseeker\022#.p" +
      "rotos.service.GetJobSeekerRequest\032$.prot" +
      "os.service.GetJobSeekerResponse\022P\n\tGetSk" +
      "ills\022 .protos.service.GetSkillsRequest\032!" +
      ".protos.service.GetSkillsResponse\022k\n\022Get" +
      "EmploymentTypes\022).protos.service.GetEmpl" +
      "oymentTypesRequest\032*.protos.service.GetE" +
      "mploymentTypesResponse\022b\n\017SearchJobseeke" +
      "r\022&.protos.service.SearchJobSeekerReques" +
      "t\032\'.protos.service.SearchJobSeekerRespon" +
      "seBw\n!com.wanpng.jobseeker.grpc.serviceB" +
      "\027JobseeekerServiceProtosP\001Z7github.com/w" +
      "anpng/job-seekers-profile-grpc/grpc/serv" +
      "iceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.getDescriptor(),
          com.wanpng.jobseeker.grpc.domain.JobSeekerSkillProtos.getDescriptor(),
          com.wanpng.jobseeker.grpc.domain.JobSeekerEmploymentTypeProtos.getDescriptor(),
        });
    internal_static_protos_service_GetJobSeekerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_service_GetJobSeekerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetJobSeekerRequest_descriptor,
        new java.lang.String[] { "JobseekerId", });
    internal_static_protos_service_GetJobSeekerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_service_GetJobSeekerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetJobSeekerResponse_descriptor,
        new java.lang.String[] { "Jobseeker", });
    internal_static_protos_service_GetJobseekersRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_service_GetJobseekersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetJobseekersRequest_descriptor,
        new java.lang.String[] { "ApplicationStatus", "JobseekerIds", });
    internal_static_protos_service_GetJobseekersResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_service_GetJobseekersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetJobseekersResponse_descriptor,
        new java.lang.String[] { "Jobseekers", });
    internal_static_protos_service_GetSkillsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protos_service_GetSkillsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetSkillsRequest_descriptor,
        new java.lang.String[] { "CandidateId", });
    internal_static_protos_service_GetSkillsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protos_service_GetSkillsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetSkillsResponse_descriptor,
        new java.lang.String[] { "Skills", });
    internal_static_protos_service_GetEmploymentTypesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protos_service_GetEmploymentTypesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetEmploymentTypesRequest_descriptor,
        new java.lang.String[] { "CandidateId", });
    internal_static_protos_service_GetEmploymentTypesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protos_service_GetEmploymentTypesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_GetEmploymentTypesResponse_descriptor,
        new java.lang.String[] { "EmploymentTypes", });
    internal_static_protos_service_SearchJobSeekerRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_protos_service_SearchJobSeekerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SearchJobSeekerRequest_descriptor,
        new java.lang.String[] { "JobseekerIds", "Keyword", });
    internal_static_protos_service_SearchJobSeekerResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_protos_service_SearchJobSeekerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_service_SearchJobSeekerResponse_descriptor,
        new java.lang.String[] { "JobseekerIds", });
    com.wanpng.jobseeker.grpc.domain.JobseekerGrpcProtos.getDescriptor();
    com.wanpng.jobseeker.grpc.domain.JobSeekerSkillProtos.getDescriptor();
    com.wanpng.jobseeker.grpc.domain.JobSeekerEmploymentTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
